### ISSUE TITLE
Left logo truncated and multi-monitor support

### ISSUE THREAD

**Issue by mhous** [piotrpdev/Windows-screenFetch-fast#2]
Nice work, Piotr!
I noticed two issues today:
1. The logo on the left hand side is truncated if there is not enough content on the right.
2. More than one monitor yields a non-sensical Resolution line.

![image](https://user-images.githubusercontent.com/14985478/176030703-f5fae267-a4a7-4849-8d24-0f30b9cecb55.png)

**Comment by piotrpdev** [comment]
1. Sorry, but I'm not sure what to do about that. There are multiple possible solutions but it could come down to preference e.g. resize logo dynamically, force whitespace, etc. and I'm not sure what everybody would want,

2. I have two monitors and it works fine so I'm not sure what the problem is; without borrowing your device there also sadly isn't a way for me to troubleshoot this myself.

Mind sending me the output of the following?

```powershell
$videoMode = Get-CimInstance Win32_VideoController;
```
```powershell
($videoMode.CurrentHorizontalResolution -join ',') + " x " + ($videoMode.CurrentVerticalResolution -join ',') + " (" + ($videoMode.CurrentRefreshRate -join ',') + "Hz)";
```

**Comment by AkariiinMKII** [comment]
Afaik `Get-CimInstance Win32_DisplayConfiguration` does not support multiple GPUs, and `Get-CimInstance -N "root\wmi" -Class WmiMonitorListedSupportedSourceModes` does not work as intended, I suggest using  `Get-CimInstance Win32_VideoController`.
As for the first issue, see https://github.com/AkariiinMKII/Windows-screenFetch/blob/8c12a501c96f04b443a1784e67c0011f7ca40a83/Windows-screenFetch.psm1#L28

**Comment by piotrpdev** [comment]
@AkariiinMKII ffs man, if I knew you made a better alternative to windows-screenfetch I wouldn't have made mine lol. Why didn't you [post an issue on the original repo so it would be easier to find](https://github.com/JulianChow94/Windows-screenFetch/issues/73)?

@mhous I fixed the logo issue ~~by yoinking Akariin's solution~~ but I suggest just installing his version, this repo has now become pointless lol.

**Comment by AkariiinMKII** [comment]
> @AkariiinMKII ffs man, if I knew you made a better alternative to windows-screenfetch I wouldn't have made mine lol. Why didn't you [post an issue on the original repo so it would be easier to find](https://github.com/JulianChow94/Windows-screenFetch/issues/73)?
> 
> @mhous I fixed the logo issue ~~by yoinking Akariin's solution~~ but I suggest just installing his version, this repo has now become pointless lol.

I've changed many codes for my own purpose that I'm not sure it's stable enough for public use, and I may not have enough time for maintenance. Feel free to use my codes in your repository :P
